# Generated by Django 4.2.5 on 2024-11-18 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.IntegerField()),
                ('skill', models.CharField(max_length=255)),
                ('question_text', models.TextField()),
                ('options', models.JSONField(blank=True, null=True)),
                ('answer', models.JSONField()),
                ('hint', models.TextField(blank=True, null=True)),
                ('question_type', models.CharField(max_length=50)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('images', models.JSONField(blank=True, null=True)),
                ('labels', models.JSONField(blank=True, null=True)),
                ('center_image', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('attempts', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
