# Generated by Django 4.2.5 on 2024-11-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_studentdata_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.RemoveField(
            model_name='question',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='question',
            name='module',
        ),
        migrations.AddField(
            model_name='question',
            name='activity',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='center_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='KnowledgeLog',
        ),
    ]
